blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_index, name="index"),
    path("<int:blog_id>/", views.detail, name="detail"),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path("", views.home, name="home"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('blog/', include('blog.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import Truncator

class Blog(models.Model):
    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    summary = models.TextField(blank=True, default='')
    image = models.ImageField(upload_to='images/', blank=True, null=True)
       
    @property
    def preview(self):
        return Truncator(self.summary).words(20)

    def __str__(self):
        return self.title
    
    def pub_date_pretty(self):
        return self.pub_date.strftime('%e %b %Y')

jobs/models.py
from django.db import models

class Job(models.Model):
    image = models.ImageField(upload_to='images/')
    summary = models.CharField(max_length=255)


def __str__(self):
        return self.summary

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog

def blog_index(request):
    blogs = Blog.objects.all().order_by('-pub_date')
    return render(request, 'blog/bloglist.html', {"blogs":blogs})

def detail(request, blog_id):
    detailblog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog/detail.html', {'blog':detailblog})

jobs/views.py
from django.shortcuts import render
from .models import Job

def home(request):
    jobs = Job.objects.all()
    return render(request, "jobs/home.html", {"jobs": jobs})

blog/templates/blog/bloglist.html
{% extends "base.html" %}
{% block title %}Blog{% endblock %}
{% load static %}
{% block content %} 
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">
  <div class="container-fluid">
    <a class="navbar-brand fw-semibold" href="{% url 'jobs:home' %}">Rebecca D Simmons</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav mb-2 mb-lg-0">
        <a class="nav-link" href="{% url 'jobs:home' %}">Jobs</a>
        <a class="nav-link" href="{% static 'VP Tech Resume 2026.pdf' %}">Resume</a>
        <a class="nav-link active" aria-current="page" href="#">Blog</a>
        <!--a class="nav-link disabled" aria-disabled="true">Disabled</a -->
      </div>
    </div>
  </div>
</nav>
<main role="main">
    <div class="container">
  <h1 class="text-center pt-3">Welcome to Rebecca's Blog</h1>
  <br>
  <br>
  <h2 class="fst-italic">Latest Posts</h2>
  <br>
<ul class="list-unstyled">
    {% for blog in blogs %}
    <li class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"> 
        <img class="img-fluid" src="{{ blog.image.url }}" aria-hidden="true" height="200" preserveAspectRatio="xMidYMid slice"
                width="200" xmlns="http://www.w3.org/2000/svg"> 
                <rect width="200" height="200" fill="#777"></rect>
                        <div class="col-lg-8">
                <a href="{% url 'blog:detail' blog.id %}"><h3 class="mb-0">{{ blog.title }}</h3></a>
                <small class="text-body-secondary">{{ blog.pub_date_pretty }}</small>
                <p>{{ blog.preview }}</p>
            </div>
    </li>
</ul>
 {% endfor %}
</div>
    </div>
</main>
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1"> <a href="#">Back to top</a> </p>
        <p class="mb-1">&copy; Rebecca D Simmons {% now "Y" %}</p>
        <!--p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction">getting started guide</a>.</p -->
    </div>
</footer> 
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}{{ blog.title }}{% endblock %}
{% load static %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">
  <div class="container-fluid">
    <a class="navbar-brand fw-semibold" href="{% url 'jobs:home' %}">Rebecca D Simmons</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav mb-2 mb-lg-0">
        <a class="nav-link" aria-current="page" href="{% url 'jobs:home' %}">Jobs</a>
        <a class="nav-link" href="{% static 'VP Tech Resume 2026.pdf' %}">Resume</a>
        <a class="nav-link active" href="#">Blog</a>
        <!--a class="nav-link disabled" aria-disabled="true">Disabled</a -->
      </div>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h1 class="text-center mt-4">{{ blog.title }}</h1>
  <p class="text-muted">{{ blog.pub_date }}</p>

  {% if blog.image %}
    <img src="{{ blog.image.url }}" class="rounded mx-auto d-block" alt="Blog image">
  {% endif %}

  <p>{{ blog.summary }}</p>
  <p class="float-center mb-1"> <a href="{% url 'blog:index' %}">Back to Blog List</a> </p>
</div>
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1"> <a href="#">Back to top</a> </p>
        <p class="mb-1">&copy; Rebecca D Simmons {% now "Y" %}</p>
        <!--p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction">getting started guide</a>.</p -->
    </div>
</footer> 
{% endblock %}

jobs/templates/jobs/home.html
{% extends "base.html" %}
{% block title %}Jobs{% endblock %}
{% load static %}
{% block content %} 
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">
  <div class="container-fluid">
    <a class="navbar-brand fw-semibold" href="{% url 'jobs:home' %}">Rebecca D Simmons</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav mb-2 mb-lg-0">
        <a class="nav-link active" aria-current="page" href="#">Jobs</a>
        <a class="nav-link" href="{% static 'VP Tech Resume 2026.pdf' %}">Resume</a>
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
        <!--a class="nav-link disabled" aria-disabled="true">Disabled</a -->
      </div>
    </div>
  </div>
</nav>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">It's Never Becky</h1>
                <p class="lead text-body-secondary">Hey! My name is Rebecca and I'm taking a Django class.</p>
                <p> <a href="#" class="btn btn-primary my-2">Email Me</a> <!--a href="#"
                        class="btn btn-secondary my-2">Secondary action</a --> </p>
                <img src="{% static 'Site_Image.jpg' %}" height = '300' />
            </div>
        </div>
    </section>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for job in jobs.all %}
                <div class="col">
                    <div class="card shadow-sm h-100">
                       <img src="{{ job.image.url }}" class="card-img-top" alt="Job image" style="height: 200px; object-fit: cover;">
                        <div class="card-body">
                            <p class="card-text">{{ job.summary }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1"> <a href="#">Back to top</a> </p>
        <p class="mb-1">&copy; Rebecca D Simmons {% now "Y" %}</p>
        <!--p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction">getting started guide</a>.</p -->
    </div>
</footer> 
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Portfolio{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">

    {% block extra_css %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- Bootstrap JS bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>